// Invoice generation — a port of the web's components/InvoiceGenerate.tsx logic
// (everything above its JSX), kept line-for-line where it can be: billing
// periods from the contract's cycle (0436), attendance-driven quantity for
// Variable clients (§10.4), effective committed counts and rates from addendums,
// persisted drafts and Cleared flags (0340), and the posting itself.
//
// One phone difference: posting a batch does not open a share sheet per invoice
// (a phone shows one at a time). Each posted invoice's PDF is one tap away in
// the invoice list, generated by the same template.
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { q, rpc, sb } from "./core";
import {
  amountInWords, computeInvoiceTaxes, CONTRACT_LINE_CATEGORY_LABEL, DEFAULT_INVOICE_SETTINGS, DEFAULT_VARIABLE_COLUMNS, effectiveCommittedByCategory,
  effectiveContractEnd, effectiveRateByLine, financialYearLabel,
  type Client, type ClientInvoiceGroup, type Contract, type ContractAddendum, type ContractLine, type Invoice, type InvoiceLine, type InvoiceTax,
  type RemitAccount, type VariableGrid,
} from "../../lib/web/supabase";

export type DraftLine = { category: InvoiceLine["category"]; label: string; quantity: string; unit_rate: string; taxable: boolean };
export type DraftTax = { name: string; rate: string; base: InvoiceTax["base"]; direction: InvoiceTax["direction"]; component?: string };
export type Draft = {
  contractId: string; contractCode: string; client: Client; invoiceNumber: string; periodStart: string; periodEnd: string; lines: DraftLine[];
  variableColumns: string[]; variableRows: string[][]; variableTotal: string; taxes: DraftTax[]; notes: string; remitIndex: number;
  overrideTotal: string; overrideReason: string; previousBalance: number; includePreviousBalance: boolean; status: "Pending" | "Cleared";
};
export type StatusFilter = "all" | "pending" | "cleared";
export type GenRow =
  | { kind: "existing"; key: string; client: Client; contract: Contract; invoice: Invoice }
  | { kind: "draft"; key: string; client: Client; contract: Contract };

export const num = (s: string) => Number(String(s).replace(/,/g, "").trim()) || 0;
const AMOUNT_COL = "Amount";
const withAmountLast = (cols: string[]) => [...cols.filter((c) => c.trim().toLowerCase() !== "amount"), AMOUNT_COL];
const monthKey = () => new Date().toISOString().slice(0, 7);
const today = () => new Date().toISOString().slice(0, 10);
const invoiceMonth = (inv: Invoice) => (inv.service_month ?? inv.period_start ?? inv.invoice_date ?? "").slice(0, 7);
const isCleared = (inv: Invoice) => inv.status === "Paid";

const periodInContractWindow = (con: Contract, ym: string, addendums: ContractAddendum[]): boolean => {
  const startMonth = (con.start_date ?? "").slice(0, 7);
  if (startMonth && ym < startMonth) return false;
  const eff = effectiveContractEnd(con, addendums);
  const endMonth = eff.isInfinite || !eff.endDate ? null : eff.endDate.slice(0, 7);
  if (endMonth && ym > endMonth) return false;
  const termMonth = con.termination_date ? con.termination_date.slice(0, 7) : null;
  if (termMonth && ym > termMonth) return false;
  return true;
};
const isInvoiceableContract = (con: Contract) => con.status !== "draft";
const monthBounds = (ym: string) => {
  const [y, m] = ym.split("-").map(Number);
  return { start: `${ym}-01`, end: `${ym}-${String(new Date(y!, m!, 0).getDate()).padStart(2, "0")}` };
};

type DraftBlob = Partial<Pick<Draft, "invoiceNumber" | "periodStart" | "periodEnd" | "notes" | "remitIndex" | "overrideTotal" | "overrideReason" | "includePreviousBalance" | "lines" | "variableColumns" | "variableRows">>;
const serializeDraft = (d: Draft): DraftBlob => ({
  invoiceNumber: d.invoiceNumber, periodStart: d.periodStart, periodEnd: d.periodEnd, notes: d.notes, remitIndex: d.remitIndex,
  overrideTotal: d.overrideTotal, overrideReason: d.overrideReason, includePreviousBalance: d.includePreviousBalance,
  lines: d.lines, variableColumns: d.variableColumns, variableRows: d.variableRows,
});
const applyBlob = (d: Draft, blob: DraftBlob | undefined): Draft => (blob ? { ...d, ...blob } : d);

export function useInvoiceGenerator(company: any | null, regionId: string | null = null) {
  const [clients, setClients] = useState<Client[]>([]);
  const [contracts, setContracts] = useState<Contract[]>([]);
  const [lines, setLines] = useState<ContractLine[]>([]);
  const [addendums, setAddendums] = useState<ContractAddendum[]>([]);
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [period, setPeriod] = useState(monthKey());
  const [group, setGroup] = useState<ClientInvoiceGroup>("FIXED");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [drafts, setDrafts] = useState<Record<string, Draft>>({});
  const [clearedKeys, setClearedKeys] = useState<Set<string>>(new Set());
  const savedData = useRef<Map<string, DraftBlob>>(new Map());
  const dirtyKeys = useRef<Set<string>>(new Set());
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const loadData = useCallback(async () => {
    setLoading(true);
    const [cli, con, lin, add, inv, drf] = await Promise.all([
      q<Client[]>(sb().from("clients").select("*").order("name")),
      q<Contract[]>(sb().from("contracts").select("*")),
      q<ContractLine[]>(sb().from("contract_lines").select("*")),
      q<ContractAddendum[]>(sb().from("contract_addendums").select("*")),
      q<Invoice[]>(sb().from("invoices").select("*")),
      q<any[]>(sb().from("invoice_generation_drafts").select("contract_id, period, data, cleared")),
    ]);
    setClients(cli); setContracts(con); setLines(lin); setAddendums(add); setInvoices(inv);
    savedData.current = new Map(drf.filter((r) => r.data && Object.keys(r.data).length > 0).map((r) => [`${r.contract_id}|${r.period}`, r.data as DraftBlob]));
    setClearedKeys(new Set(drf.filter((r) => r.cleared).map((r) => `${r.contract_id}|${r.period}`)));
    setLoading(false);
  }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect -- load-on-change, as the web screen does
  useEffect(() => { void loadData(); }, [loadData]);

  // Region selector: only the selected region's clients are drafted/listed; invoices
  // still load company-wide so numbering dedupes against every taken number.
  const regionClients = useMemo(() => (regionId ? clients.filter((c) => c.branch_id === regionId) : clients), [clients, regionId]);
  const groupClients = useMemo(() => regionClients.filter((c) => (c.invoice_group ?? "FIXED") === group), [regionClients, group]);

  const [billingPeriods, setBillingPeriods] = useState<Map<string, { start: string; end: string }>>(new Map());
  useEffect(() => {
    let alive = true;
    rpc<any[]>("billing_periods_for_month", { p_month: `${period}-01` }).then((data) => {
      if (!alive) return;
      const m = new Map<string, { start: string; end: string }>();
      for (const r of data ?? []) {
        const cur = m.get(r.contract_id);
        if (!cur || r.period_start > cur.start) m.set(r.contract_id, { start: r.period_start, end: r.period_end });
      }
      setBillingPeriods(m);
    }).catch(() => {});
    return () => { alive = false; };
  }, [period]);

  const [attQty, setAttQty] = useState<Map<string, number>>(new Map());
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- load-on-change, as the web screen does
    if (group !== "VARIABLE") { setAttQty(new Map()); return; }
    let alive = true;
    (async () => {
      const entries = await Promise.all(groupClients.map(async (c) => {
        const con = contracts.find((k) => k.client_id === c.id && billingPeriods.has(k.id));
        const { start, end } = (con && billingPeriods.get(con.id)) || monthBounds(period);
        const data = await rpc<number>("attendance_billable_quantity", { p_client: c.id, p_start: start, p_end: end }).catch(() => 0);
        return [c.id, Number(data) || 0] as [string, number];
      }));
      if (alive) setAttQty(new Map(entries));
    })();
    return () => { alive = false; };
  }, [group, period, groupClients, contracts, billingPeriods]);

  const suggestNumber = useCallback((client: Client, taken: Set<string>): string => {
    const settings = { ...DEFAULT_INVOICE_SETTINGS, ...(company?.invoice_settings ?? {}) };
    const initials = (name?: string | null) => (name ?? "").split(/\s+/).filter((w) => /^[A-Za-z]/.test(w)).slice(0, 3).map((w) => w[0]!.toUpperCase()).join("");
    const companyPrefix = (settings.company_prefix?.trim() || initials(company?.legal_name || company?.name) || "INV").toUpperCase();
    const clientPrefix = (client.employee_id_prefix?.trim() || client.client_code || "CLT").toUpperCase();
    const base = `${companyPrefix}-${period.slice(2, 4)}-${clientPrefix}-${period.slice(5, 7)}`;
    if (!taken.has(base)) return base;
    let n = 2;
    while (taken.has(`${base}-${n}`)) n++;
    return `${base}-${n}`;
  }, [period, company]);

  const contractPreviousBalance = useCallback((contractId: string): number => {
    const settings = { ...DEFAULT_INVOICE_SETTINGS, ...(company?.invoice_settings ?? {}) };
    const enabled = group === "VARIABLE" ? settings.variable_show_previous_balance : group === "FIXED" ? settings.fixed_show_previous_balance : false;
    if (!enabled) return 0;
    const priors = invoices.filter((i) => i.contract_id === contractId && invoiceMonth(i) < period).sort((a, b) => (invoiceMonth(a) < invoiceMonth(b) ? 1 : -1));
    const last = priors[0];
    if (!last) return 0;
    const unpaid = last.status === "Unpaid" || last.status === "Pending" || last.status === "Partly-Paid";
    if (!unpaid) return 0;
    return Math.max(0, Number(last.total_due ?? last.invoice_amount ?? 0) - Number(last.amount_received ?? 0));
  }, [invoices, period, group, company]);

  const buildDraft = useCallback((client: Client, con: Contract, taken: Set<string>): Draft | null => {
    const { start, end } = billingPeriods.get(con.id) ?? monthBounds(period);
    const remitIndex = Math.max(0, (client.remit_accounts ?? []).findIndex((r) => r.is_default));
    if ((client.invoice_group ?? "FIXED") === "VARIABLE") {
      const columns = withAmountLast(client.variable_columns && client.variable_columns.length > 0 ? client.variable_columns : DEFAULT_VARIABLE_COLUMNS);
      const number = suggestNumber(client, taken);
      taken.add(number);
      return {
        contractId: con.id, contractCode: con.contract_code, client, invoiceNumber: number, periodStart: start, periodEnd: end, lines: [],
        variableColumns: columns, variableRows: [columns.map(() => "")], variableTotal: "", taxes: [], notes: "", remitIndex,
        overrideTotal: "", overrideReason: "", previousBalance: contractPreviousBalance(con.id), includePreviousBalance: true, status: "Pending",
      };
    }
    const conLines = lines.filter((l) => l.contract_id === con.id);
    const conAdds = addendums.filter((a) => a.contract_id === con.id);
    const eff = effectiveCommittedByCategory(conLines, conAdds, end);
    const effRate = effectiveRateByLine(conLines, conAdds, end);
    const draftLines: DraftLine[] = [];
    for (const l of conLines) {
      const single = conLines.filter((x) => x.category === l.category).length === 1;
      const attributed = group === "VARIABLE" && l.category === "GUARD" ? attQty.get(client.id) : undefined;
      const qty = attributed != null && attributed > 0 ? attributed : single && eff.get(l.category) != null ? eff.get(l.category)! : l.committed_count;
      const rate = effRate.get(l.id) ?? l.unit_rate;
      if (qty <= 0 && rate <= 0) continue;
      draftLines.push({ category: l.category, label: l.label ?? CONTRACT_LINE_CATEGORY_LABEL[l.category], quantity: String(qty), unit_rate: String(rate), taxable: l.taxable });
    }
    if (draftLines.length === 0) return null;
    // A1: bill GROSS — WITHHELD entries never reach an invoice.
    const taxes: DraftTax[] = (client.tax_profile ?? []).filter((t) => t.direction !== "WITHHELD")
      .map((t) => ({ name: t.name, rate: String(t.rate), base: t.base, direction: t.direction, component: t.component }));
    const number = suggestNumber(client, taken);
    taken.add(number);
    return {
      contractId: con.id, contractCode: con.contract_code, client, invoiceNumber: number, periodStart: start, periodEnd: end, lines: draftLines,
      variableColumns: [], variableRows: [], variableTotal: "", taxes, notes: "", remitIndex, overrideTotal: "", overrideReason: "",
      previousBalance: contractPreviousBalance(con.id), includePreviousBalance: true, status: "Pending",
    };
  }, [period, lines, addendums, suggestNumber, contractPreviousBalance, group, attQty, billingPeriods]);

  useEffect(() => {
    if (loading) return;
    const taken = new Set(invoices.map((i) => i.invoice_number.trim().toLowerCase()));
    const next: Record<string, Draft> = {};
    for (const client of groupClients) {
      for (const con of contracts.filter((c) => c.client_id === client.id && isInvoiceableContract(c))) {
        if (!periodInContractWindow(con, period, addendums.filter((a) => a.contract_id === con.id))) continue;
        // 0357: primaries only.
        if (invoices.some((i) => i.contract_id === con.id && invoiceMonth(i) === period && (i.invoice_kind ?? "primary") === "primary")) continue;
        const d = buildDraft(client, con, taken);
        if (d) {
          const withBlob = applyBlob(d, savedData.current.get(`${con.id}|${period}`));
          taken.add(withBlob.invoiceNumber.trim().toLowerCase());
          withBlob.status = clearedKeys.has(`${con.id}|${period}`) ? "Cleared" : "Pending";
          next[con.id] = withBlob;
        }
      }
    }
    // eslint-disable-next-line react-hooks/set-state-in-effect -- load-on-change, as the web screen does
    setDrafts(next);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, period, group, groupClients, contracts, lines, addendums, invoices, clearedKeys, buildDraft]);

  const rows = useMemo<GenRow[]>(() => {
    const out: GenRow[] = [];
    for (const client of groupClients) {
      for (const con of contracts.filter((c) => c.client_id === client.id && isInvoiceableContract(c))) {
        const existing = invoices.find((i) => i.contract_id === con.id && invoiceMonth(i) === period && (i.invoice_kind ?? "primary") === "primary");
        if (existing) out.push({ kind: "existing", key: con.id, client, contract: con, invoice: existing });
        else if (drafts[con.id]) out.push({ kind: "draft", key: con.id, client, contract: con });
      }
    }
    return out.filter((r) => {
      if (statusFilter === "all") return true;
      const cleared = r.kind === "existing" ? isCleared(r.invoice) : drafts[r.key]?.status === "Cleared";
      return statusFilter === "cleared" ? cleared : !cleared;
    });
  }, [groupClients, contracts, invoices, drafts, period, statusFilter]);

  const outOfWindowInvoices = useMemo(() => {
    const byId = new Map(contracts.map((c) => [c.id, c]));
    const out: { inv: Invoice; con: Contract; clientName: string }[] = [];
    for (const inv of invoices) {
      if (!inv.contract_id) continue;
      const con = byId.get(inv.contract_id);
      if (!con || periodInContractWindow(con, invoiceMonth(inv), addendums.filter((a) => a.contract_id === con.id))) continue;
      const client = regionClients.find((c) => c.id === con.client_id);
      if (!client) continue; // outside the selected region
      out.push({ inv, con, clientName: client.name });
    }
    return out.sort((a, b) => (invoiceMonth(a.inv) < invoiceMonth(b.inv) ? -1 : 1));
  }, [invoices, contracts, regionClients, addendums]);

  const variableAmountTotal = (d: Draft) => {
    const c = d.variableColumns.length - 1;
    return c < 0 ? 0 : d.variableRows.reduce((s, row) => s + num(row[c] ?? ""), 0);
  };

  const figures = useCallback((d: Draft) => {
    const carried = d.includePreviousBalance ? d.previousBalance : 0;
    if ((d.client.invoice_group ?? "FIXED") === "VARIABLE") {
      const gross = variableAmountTotal(d);
      const lineTotal = gross + carried;
      return { subtotal: gross, computed: [] as ReturnType<typeof computeInvoiceTaxes>["computed"], addedTotal: 0, withheldTotal: 0, lineTotal, totalDue: lineTotal, carried, overridden: false };
    }
    const subtotal = d.lines.reduce((s, l) => s + num(l.quantity) * num(l.unit_rate), 0);
    const { computed, addedTotal, withheldTotal } = computeInvoiceTaxes(subtotal, d.taxes.map((t) => ({ name: t.name, rate: num(t.rate), base: t.base, direction: t.direction, component: t.component ?? null })));
    const lineTotal = subtotal + addedTotal - withheldTotal + carried;
    const overridden = d.overrideTotal.trim() !== "" && num(d.overrideTotal) !== lineTotal;
    return { subtotal, computed, addedTotal, withheldTotal, lineTotal, totalDue: overridden ? num(d.overrideTotal) : lineTotal, carried, overridden };
  }, []);

  const flushSaves = useCallback(async () => {
    const keys = [...dirtyKeys.current];
    dirtyKeys.current.clear();
    for (const key of keys) {
      const blob = savedData.current.get(key);
      if (!blob) continue;
      const [contractId, per] = key.split("|");
      const { data: upd, error: e } = await sb().from("invoice_generation_drafts").update({ data: blob, updated_at: new Date().toISOString() } as never).eq("contract_id", contractId!).eq("period", per!).select("id");
      if (e || (upd && upd.length > 0)) continue;
      const { error: insE } = await sb().from("invoice_generation_drafts").insert({ contract_id: contractId, period: per, data: blob } as never);
      if (insE && /duplicate key/i.test(insE.message)) {
        await sb().from("invoice_generation_drafts").update({ data: blob, updated_at: new Date().toISOString() } as never).eq("contract_id", contractId!).eq("period", per!);
      }
    }
  }, []);
  useEffect(() => () => { if (saveTimer.current) clearTimeout(saveTimer.current); void flushSaves(); }, [flushSaves]);

  const patchDraft = (contractId: string, patch: Partial<Draft>) => {
    const cur = drafts[contractId];
    if (!cur) return;
    const nextD = { ...cur, ...patch };
    const key = `${contractId}|${period}`;
    savedData.current.set(key, serializeDraft(nextD));
    setDrafts((prev) => (prev[contractId] ? { ...prev, [contractId]: nextD } : prev));
    dirtyKeys.current.add(key);
    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => { void flushSaves(); }, 700);
  };

  const grid = {
    setHeader: (id: string, c: number, val: string) => { const d = drafts[id]; if (!d || c === d.variableColumns.length - 1) return; patchDraft(id, { variableColumns: d.variableColumns.map((h, i) => (i === c ? val : h)) }); },
    setCell: (id: string, r: number, c: number, val: string) => patchDraft(id, { variableRows: drafts[id]?.variableRows.map((row, ri) => (ri === r ? row.map((cell, ci) => (ci === c ? val : cell)) : row)) }),
    addColumn: (id: string) => { const d = drafts[id]; if (!d) return; const at = Math.max(0, d.variableColumns.length - 1); patchDraft(id, { variableColumns: [...d.variableColumns.slice(0, at), `Column ${d.variableColumns.length}`, ...d.variableColumns.slice(at)], variableRows: d.variableRows.map((row) => [...row.slice(0, at), "", ...row.slice(at)]) }); },
    removeColumn: (id: string, c: number) => { const d = drafts[id]; if (!d || d.variableColumns.length <= 1 || c === d.variableColumns.length - 1) return; patchDraft(id, { variableColumns: d.variableColumns.filter((_, i) => i !== c), variableRows: d.variableRows.map((row) => row.filter((_, i) => i !== c)) }); },
    addRow: (id: string) => { const d = drafts[id]; if (!d) return; patchDraft(id, { variableRows: [...d.variableRows, d.variableColumns.map(() => "")] }); },
    removeRow: (id: string, r: number) => { const d = drafts[id]; if (!d) return; patchDraft(id, { variableRows: d.variableRows.filter((_, i) => i !== r) }); },
  };

  /** toggleCleared(): persist the flag (update-or-insert), carrying current edits into an insert. */
  const toggleCleared = async (contractId: string) => {
    const key = `${contractId}|${period}`;
    const willClear = !clearedKeys.has(key);
    const blob = savedData.current.get(key) ?? (drafts[contractId] ? serializeDraft(drafts[contractId]!) : {});
    const { data: upd, error: updErr } = await sb().from("invoice_generation_drafts").update({ cleared: willClear, updated_at: new Date().toISOString() } as never).eq("contract_id", contractId).eq("period", period).select("id");
    if (updErr) throw new Error(updErr.message);
    if (!upd || upd.length === 0) {
      const { error: insE } = await sb().from("invoice_generation_drafts").insert({ contract_id: contractId, period, cleared: willClear, data: blob } as never);
      if (insE && !/duplicate key/i.test(insE.message)) throw new Error(insE.message);
    }
    setClearedKeys((prev) => { const n = new Set(prev); if (willClear) n.add(key); else n.delete(key); return n; });
  };

  const postDraft = async (d: Draft) => {
    const f = figures(d);
    const isVariable = (d.client.invoice_group ?? "FIXED") === "VARIABLE";
    const remit: RemitAccount | null = (d.client.remit_accounts ?? [])[d.remitIndex] ?? null;
    const variableGrid: VariableGrid | null = isVariable ? { columns: d.variableColumns, rows: d.variableRows, total: variableAmountTotal(d) } : null;
    const { data: ins, error: insErr } = await sb().from("invoices").insert({
      client_id: d.client.id, contract_id: d.contractId, invoice_number: d.invoiceNumber.trim(), invoice_date: today(), invoice_amount: f.subtotal + f.addedTotal,
      amount_received: 0, status: "Unpaid", notes: d.notes.trim() || null, period_start: d.periodStart, period_end: d.periodEnd, subtotal: f.subtotal,
      tax_added_total: f.addedTotal, tax_withheld_total: f.withheldTotal, previous_balance: f.carried, total_due: f.totalDue, amount_in_words: amountInWords(f.totalDue),
      remit_account: remit, override_reason: f.overridden ? d.overrideReason.trim() : null, financial_year: financialYearLabel(`${period}-01`),
      invoice_group: group, variable_grid: variableGrid, generated: true,
    } as never).select().single();
    if (insErr) {
      const dup = /uq_invoice_contract_month|duplicate key/i.test(insErr.message);
      throw new Error(dup ? `${d.client.name} (${d.contractCode}): an invoice for this contract already exists for ${period}.` : `${d.client.name} (${d.invoiceNumber}): ${insErr.message}`);
    }
    const invoice = ins as Invoice;
    const lineRows = d.lines.map((l, i) => ({ invoice_id: invoice.id, category: l.category, label: l.label, quantity: Math.floor(num(l.quantity)), unit_rate: num(l.unit_rate), amount: num(l.quantity) * num(l.unit_rate), taxable: l.taxable, sort_order: i }));
    if (lineRows.length) await q(sb().from("invoice_lines").insert(lineRows as never));
    const taxRows = f.computed.map((t, i) => ({ invoice_id: invoice.id, name: t.name, rate: t.rate, base: t.base, direction: t.direction, component: t.component ?? null, amount: t.amount, sort_order: i }));
    if (taxRows.length) await q(sb().from("invoice_taxes").insert(taxRows as never));
    if (isVariable) await sb().from("clients").update({ variable_columns: d.variableColumns } as never).eq("id", d.client.id);
  };

  /** generateAllCleared(): every guard up front, then post in order; stops and reports on the first failure. */
  const generateAllCleared = async (): Promise<string> => {
    const cleared = Object.values(drafts).filter((d) => d.status === "Cleared");
    if (cleared.length === 0) throw new Error("Clear at least one draft first.");
    const existingNumbers = new Set(invoices.map((i) => i.invoice_number.trim().toLowerCase()));
    const seen = new Set<string>();
    for (const d of cleared) {
      const f = figures(d);
      if (f.overridden && !d.overrideReason.trim()) throw new Error(`${d.client.name}: an override total needs a reason.`);
      const key = d.invoiceNumber.trim().toLowerCase();
      if (existingNumbers.has(key)) throw new Error(`${d.client.name} (${d.invoiceNumber}): that invoice number already exists.`);
      if (seen.has(key)) throw new Error(`Invoice number ${d.invoiceNumber} is used by more than one draft in this batch.`);
      seen.add(key);
      if (invoices.some((i) => i.contract_id === d.contractId && invoiceMonth(i) === period)) throw new Error(`${d.client.name} (${d.contractCode}): this contract already has an invoice for ${period}.`);
    }
    let posted = 0;
    try {
      for (const d of cleared) { await postDraft(d); posted++; }
      await sb().from("invoice_generation_drafts").delete().in("contract_id", cleared.map((d) => d.contractId)).eq("period", period);
      return `Posted ${posted} invoice${posted === 1 ? "" : "s"} as Unpaid. Download each PDF from the invoice list.`;
    } catch (err) {
      throw new Error(`${err instanceof Error ? err.message : String(err)}${posted > 0 ? ` (${posted} already posted before this)` : ""}`);
    } finally {
      await loadData();
    }
  };

  return {
    loading, period, setPeriod, group, setGroup, statusFilter, setStatusFilter, drafts, rows, outOfWindowInvoices,
    figures, patchDraft, grid, toggleCleared, generateAllCleared, reload: loadData, contracts, lines,
  };
}
