// Copy the web app's pure helpers (src/app/lib) into mobile/src/lib/web/ so the
// phone runs the SAME code for PDFs, Excel, attendance windows and validation —
// not a re-implementation that drifts. Run after changing any of them on the web:
//
//   node scripts/sync-web-lib.mjs
//
// Files are copied verbatim except for the small, listed patches below. Every
// patch is asserted to apply exactly once, so a web change that moves the
// anchor fails this script loudly instead of shipping a half-patched copy.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const WEB = join(here, "..", "..", "src", "app", "lib");
const OUT = join(here, "..", "src", "lib", "web");
mkdirSync(OUT, { recursive: true });

const FILES = [
  "supabase.ts", "date.ts", "employmentWindow.ts", "shiftOnDate.ts", "attendanceDay.ts", "guardCode.ts",
  "attendanceSummary.ts", "attendanceSheet.ts", "attendanceSheetPdf.ts", "excel.ts", "pdfBranding.ts",
  "invoicePdf.ts", "invoiceTemplates.ts", "idCardPdf.ts", "employeeFormPdf.ts", "dischargeSheetPdf.ts",
  "clearanceCertificatePdf.ts", "clientReportPdf.ts", "dailyReportPdf.ts", "depositSlip.ts", "custodian.ts",
  "monthRange.ts", "employeeExportFields.ts", "validation.ts", "billing.ts", "pricing.ts",
];

function once(src, file, from, to) {
  const n = src.split(from).length - 1;
  if (n !== 1) throw new Error(`${file}: patch anchor found ${n} times (expected 1): ${from.slice(0, 80)}`);
  return src.replace(from, to);
}

const PATCHES = {
  // The browser client → the phone's client (AsyncStorage session, same project).
  "supabase.ts": (s, f) => {
    s = once(s, f, `import { createClient } from "@supabase/supabase-js";\n\nconst url = import.meta.env.VITE_SUPABASE_URL as string;\nconst anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string;\n`,
      `import { supabase as phoneClient } from "../supabase";\n`);
    const start = s.indexOf("const permissionAwareFetch");
    const end = s.indexOf("// Paginate through a Supabase query");
    if (start < 0 || end < 0) throw new Error(`${f}: client block anchors missing`);
    return s.slice(0, start) + `// PATCHED (sync-web-lib): the phone creates its client in ../supabase.ts,\n// with the same permission-friendly fetch.\nexport const supabase = phoneClient!;\n\n` + s.slice(end);
  },
  // RN cannot construct a Blob from an ArrayBuffer.
  "excel.ts": (s, f) => {
    s = once(s, f, `import { saveBlob, mimeFor } from "./saveFile";`, `import { saveBytes } from "../saveFile";`);
    return once(s, f, `  void saveBlob(new Blob([bytes], { type: mimeFor(fileName) }), fileName);`, `  void saveBytes(bytes, fileName);`);
  },
};

// pricing.ts on the web is a one-line re-export of the file the edge functions
// share; the phone takes that shared file itself.
const SOURCE = { "pricing.ts": join(here, "..", "..", "supabase", "functions", "_shared", "pricing.ts") };

for (const file of FILES) {
  let src = readFileSync(SOURCE[file] ?? join(WEB, file), "utf8").replace(/\r\n/g, "\n");
  if (PATCHES[file]) src = PATCHES[file](src, file);
  // The phone's saveFile lives one level up.
  src = src.replace(/from "\.\/saveFile"/g, 'from "../saveFile"');
  const header = `// GENERATED by scripts/sync-web-lib.mjs from src/app/lib/${file} — do not edit here;\n// change the web file and re-run the script.\n`;
  writeFileSync(join(OUT, file), header + src);
}
console.log(`synced ${FILES.length} files → src/lib/web/`);
